<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>TechFixStudio</AssemblyName>
    <RootNamespace>TechFixStudio</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="app.manifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

</Project>